/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.xkerman;

import io.webfolder.ui4j.api.browser.BrowserEngine;
import io.webfolder.ui4j.api.browser.BrowserFactory;
import io.webfolder.ui4j.api.browser.Page;

public class App {
    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            return;
        }

        try {
            BrowserEngine engine = BrowserFactory.getWebKit();
            Page page = engine.navigate(args[0]);
            page.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
